apiVersion: skaffold/v2alpha3
kind: Config
deploy: 
  kubectl:
    manifests:
      - ./infra/kubernetes/*
build: 
  local: 
    push: false
  artifacts:
    - image: tylerg509/client
      context: clientapp
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: tylerg509/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: '*.js'
            dest: .
    - image: tylerg509/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: '*.js'
            dest: .
    - image: tylerg509/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: '*.js'
            dest: .
    - image: tylerg509/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: '*.js'
            dest: .
    - image: tylerg509/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: '*.js'
            dest: .